name: prestashop_api
description: A Dart package designed to simplify interaction with PrestaShop websites by providing 
  streamlined API integration, automatic model generation, data serialization, and exception 
  handling.
version: 0.0.1
homepage: https://github.com/MouradJEMAIL/prestashop_api
repository: https://github.com/MouradJEMAIL/prestashop_api
issue_tracker: https://github.com/MouradJEMAIL/prestashop_api/issues
topics:
  - api
  - prestashop
  - ecommerce
  - rest
  - webservice

environment:
  sdk: '>=3.2.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  dart_code_metrics: ^5.7.6
  dio: ^5.4.2+1
  freezed_annotation: ^2.4.1
  injectable: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  lint: ^2.3.0
  mockito: ^5.4.4
  test: ^1.25.3

dependency_overrides:
  analyzer: '6.4.1'
  meta: '1.11.0'
