name: prestashop_api
description: A Dart package designed to simplify interaction with PrestaShop websites by providing 
  streamlined API integration, automatic model generation, data serialization, and exception 
  handling.
version: 0.0.1
homepage: https://github.com/MouradJEMAIL/prestashop_api
repository: https://github.com/MouradJEMAIL/prestashop_api
issue_tracker: https://github.com/MouradJEMAIL/prestashop_api/issues
topics:
  - api
  - prestashop
  - ecommerce
  - flutter
  - dart
  - rest
  - webservice

environment:
  sdk: '>=3.2.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
